### Get all job applications
GET http://localhost:8080/api/job-applications
Accept: application/json

### Get all job applications with one particular status
GET http://localhost:8080/api/job-applications?status=APPLIED
Accept: application/json

### Get all job applications with one of multiple statuses
GET http://localhost:8080/api/job-applications?status=APPLIED,REJECTED
Accept: application/json


### Get job application by ID
GET http://localhost:8080/api/job-applications/1
Accept: application/json

### Create a new job application
POST http://localhost:8080/api/job-applications
Content-Type: application/json

{
  "company": "Atlassian",
  "role": "Developer",
  "status": "APPLIED"
}

### Fully update a new job application
PUT http://localhost:8080/api/job-applications/6
Content-Type: application/json

{
  "company": "Leidos",
  "role": "Engineer",
  "status": "REJECTED"
}

### Partially update a new job application
PATCH http://localhost:8080/api/job-applications/6
Content-Type: application/json

{
  "company": "OpenAI"
}

### Delete an existing job application
DELETE http://localhost:8080/api/job-applications/5
Accept: application/json

