### Get job application by ID
GET http://localhost:8080/api/job-applications/1
Accept: application/json

### Create a new job application
POST http://localhost:8080/api/job-applications
Content-Type: application/json

{
  "company": "Atlassian",
  "role": "Developer",
  "status": "APPLIED"
}

### Delete an existing job application
DELETE http://localhost:8080/api/job-applications/1
Accept: application/json

